# Default values for cray-shared-kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

kafka:
  replicas: 3
  image:
    repository: strimzi/kafka
    tag: 0.15.0-kafka-2.2.1-noJSM-chainsaw
  tlsSideCar:
    image: 
      repository: strimzi/kafka
      tag: 0.15.0-kafka-2.3.1-noJSM-chainsaw
  clusterCA:
    generateCertificateAuthority: true
    validityDays: 730
    renewalDays: 60
  clientsCA:
    generateCertificateAuthority: true
    validityDays: 365
    renewalDays: 15
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: strimzi.io/name
                operator: In
                values:
                - cray-shared-kafka-kafka
            topologyKey: "kubernetes.io/hostname"
  resources:
    limits:
      cpu: "6"
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 64Mi

zookeeper:
  image:
    repository: strimzi/kafka
    tag: 0.15.0-kafka-2.3.1-noJSM-chainsaw
  tlsSideCar:
    image:
      repository: strimzi/kafka
      tag: 0.15.0-kafka-2.3.1-noJSM-chainsaw
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: strimzi.io/name
                operator: In
                values:
                - cray-shared-kafka-zookeeper
            topologyKey: "kubernetes.io/hostname"
  resources:
    limits:
      cpu: "4"
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 64Mi

entityOperator:
  tlsSideCar:
    image:
      repository: strimzi/kafka
      tag: 0.15.0-kafka-2.3.1-noJSM-chainsaw
